retargeting:
  type: DexPilot
  urdf_path: ability_hand/ability_hand_left.urdf

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: [ 'thumb_q1', 'thumb_q2', 'index_q1', 'middle_q1', 'pinky_q1', 'ring_q1' ]
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "thumb_tip",  "index_tip", "middle_tip", "ring_tip", "pinky_tip" ]
  scaling_factor: 1.0

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2
